apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: kubernetes.io/basic-auth
stringData:
  username: mkarim09 # required field for kubernetes.io/basic-auth
  password: Mosharaf@1999 # required field for kubernetes.io/basic-auth